<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function assignment_feedback_menu()
{
  $items = array();

  /* add feedback */
  $items['feedback/add'] = array(
    'title' => 'Submit Assignment Feedback',
    'description' => 'Submit Assignment Feedback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('add_feedback_form'),
    'access arguments' => array('create assignment feedback'),
    'type' => MENU_CALLBACK,
    'file' => 'feedback.inc',
  );

  /* manage feedback */
  $items['feedback/manage'] = array(
    'title' => 'Manage Feedback',
    'description' => 'Manage Assignment Feedback',
    'page callback' => '_pending_feedbacks',
    'access callback' => 'user_access',
    'access arguments' => array('manage assignment feedback'),
    'file' => 'manage_feedback.inc',
  );
  $items['feedback/manage/pending'] = array(
    'title' => 'Pending Feedback',
    'description' => 'Pending Assignment Feedback',
    'page callback' => '_pending_feedbacks',
    'access callback' => 'user_access',
    'access arguments' => array('manage assignment feedback'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'manage_feedback.inc',
    'weight' => 2,
  );
  $items['feedback/manage/all'] = array(
    'title' => 'All Feedback',
    'description' => 'All Assignment Feedback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('all_feedbacks_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage assignment feedback'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'manage_feedback.inc',
    'weight' => 3,
  );
  $items['feedback/manage/approve'] = array(
    'title' => 'Manage Assignment Feedback',
    'description' => 'Manage Assignment Feedback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('manage_feedback_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage assignment feedback'),
    'type' => MENU_CALLBACK,
    'file' => 'manage_feedback.inc',
    'weight' => 4,
  );
  $items['feedback/manage/edit'] = array(
    'title' => 'Edit Assignment Feedback',
    'description' => 'Edit Assignment Feedback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('edit_feedback_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage assignment feedback'),
    'type' => MENU_CALLBACK,
    'file' => 'manage_feedback.inc',
    'weight' => 5,
  );

  /* for admin */
  $items['admin/settings/assignment_feedback'] = array(
    'title' => 'Assignment Feedback Settings',
    'description' => 'Assignment Feedback Settings', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('assignment_feedback_settings_form'),
    'access arguments' => array('administer assignment feedback'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function assignment_feedback_perm() {
  return array('administer assignment feedback', 'create assignment feedback', 'manage assignment feedback');
}

/**
 * Implementation of hook_link().
 */
function assignment_feedback_link($type, $object, $teaser = FALSE) {
  $links = array();

  if (in_array($object->type, variable_get('assignment_feedback_node_types', array()))) {
    $links['feedback/add'] = array(
      'title' => 'Submit Your Feedback',
      'href' => 'feedback/add/' . $object->nid,
    );
  }
  return $links;
}

/**
 * Implementation of hook_mail().
 */
function assignment_feedback_mail($key, &$message, $params) {
  global $user;
  $language = $message['language'];

  switch ($key)
  {
    case 'feedback_received':
      $user_data = user_load($params['feedback_received']['user_id']);

      $message['subject'] = t('[!site_name] We have received your feedback', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

We have received your following feedback:

Your Email: ' . $user_data->mail . '
Name of the tutorial: ' . $params['feedback_received']['tutorial_name'] . '
Feedback Type: ' . $params['feedback_received']['feedback_type'] . '
Where: ' . $params['feedback_received']['feedback_where'] . '
Start Time: ' . $params['feedback_received']['timing'] . '
How long did you take to complete the assignment: ' . $params['feedback_received']['completion_time'] . '

Comment Box :
' . $params['feedback_received']['comments'] . '

Best Wishes,

!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'feedback_approved':
      $user_data = user_load($params['feedback_approved']['user_id']);

      $message['subject'] = t('[!site_name] Your feedback has been approved', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

We have approved your following feedback:

Your Email: ' . $user_data->mail . '
Name of the tutorial: ' . $params['feedback_approved']['tutorial_name'] . '
Feedback Type: ' . $params['feedback_approved']['feedback_type'] . '
Where: ' . $params['feedback_approved']['feedback_where'] . '
Start Time: ' . $params['feedback_approved']['timing'] . '
How long did you take to complete the assignment: ' . $params['feedback_approved']['completion_time'] . '

Comment Box :
' . $params['feedback_approved']['comments'] . '

Best Wishes,

!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'feedback_disapproved':
      $user_data = user_load($params['feedback_disapproved']['user_id']);

      $message['subject'] = t('[!site_name] Your feedback has been disapproved', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

We have disapproved your following feedback:

Your Email: ' . $user_data->mail . '
Name of the tutorial: ' . $params['feedback_disapproved']['tutorial_name'] . '
Feedback Type: ' . $params['feedback_disapproved']['feedback_type'] . '
Where: ' . $params['feedback_disapproved']['feedback_where'] . '
Start Time: ' . $params['feedback_disapproved']['timing'] . '
How long did you take to complete the assignment: ' . $params['feedback_disapproved']['completion_time'] . '

Comment Box:
' . $params['feedback_disapproved']['comments'] . '

Reason for disapproval:
' . $params['feedback_disapproved']['reason'] . '

Best Wishes,

!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;
  }
}


